import type { Product } from "./types";

const now = "2026-08-01T10:00:00.000Z";

function p(product: Omit<Product, "createdAt" | "updatedAt" | "reviewCount"> & { reviews: Product["reviews"] }): Product {
  return {
    ...product,
    reviewCount: product.reviews.length,
    createdAt: now,
    updatedAt: now,
  };
}

export function seedProducts(): Product[] {
  return [
    p({
      id: "voske-aurora-ring",
      sku: "VOSKE-585-R-001",
      slug: "koltso-brilliant-severnoe-siyanie",
      name: "Кольцо «Северное сияние» с бриллиантом",
      nameHy: "«Հյուսիսափայլ» մատանի ադամանդով",
      description:
        "Классическое кольцо из красного золота 585 пробы с центральным бриллиантом круглой огранки. Модель в духе хитов 585*Золотой: чистая линия каста, тонкая шинкa и игра света на грани камня. Подходит как помолвочное украшение и как вечерний акцент.",
      price: 89900,
      oldPrice: 124900,
      category: "rings",
      metal: "rose",
      purity: 585,
      weight: 2.14,
      gender: "women",
      sizes: ["15.5", "16", "16.5", "17", "17.5", "18"],
      stones: ["бриллиант"],
      collection: "Сияние камней",
      origin: "russia",
      inspiredBy: "585*Золотой",
      inStock: true,
      stockCount: 6,
      isHit: true,
      isNew: false,
      images: ["/images/product-ring-diamond.jpg"],
      article: "R-AURORA-585",
      warrantyMonths: 24,
      rating: 4.9,
      reviews: [
        {
          author: "Анна К.",
          rating: 5,
          text: "Камень играет даже при дневном свете. Размер сел идеально, коробка как в бутике.",
          date: "2026-06-12",
          city: "Москва",
        },
        {
          author: "Мария С.",
          rating: 5,
          text: "Заказывала как подарок. Муж сказал, что выглядит дороже цены.",
          date: "2026-05-03",
          city: "Краснодар",
        },
      ],
    }),
    p({
      id: "voske-yerevan-drops",
      sku: "VOSKE-585-E-014",
      slug: "sergi-kapli-erevan",
      name: "Серьги-капли «Ереван»",
      nameHy: "«Երևան» կաթիլ ականջօղեր",
      description:
        "Удлинённые серьги из жёлтого золота с алмазной гранью. Силуэт вдохновлён витринами ереванских ювелирных домов: тёплый металл, мягкий блеск и ощущение вечернего света каскада. Лёгкие, удобны на весь день.",
      price: 45900,
      oldPrice: 52900,
      category: "earrings",
      metal: "yellow",
      purity: 585,
      weight: 3.42,
      gender: "women",
      sizes: [],
      stones: [],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "Ереванский филигранный двор",
      inStock: true,
      stockCount: 8,
      isHit: true,
      isNew: true,
      images: ["/images/product-earrings-gold.jpg"],
      article: "E-YEREVAN-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Лилит А.",
          rating: 5,
          text: "Носила на свадьбу сестры в Эчмиадзине. Золото тёплое, как армянское солнце.",
          date: "2026-07-19",
          city: "Ереван",
        },
      ],
    }),
    p({
      id: "voske-nar-necklace",
      sku: "VOSKE-585-N-007",
      slug: "kole-nar-granat",
      name: "Колье «Нар» с гранатовым зерном",
      nameHy: "«Նուռ» վզնոց նռան հատիկով",
      description:
        "Тонкая цепь и кулон-гранат — символ Армении, плодородия и дома. Гранаты глубокого вина в оправе жёлтого золота 585. Украшение, которое читается и в Москве, и в Гюмри: нежный повседневный талисман.",
      price: 67200,
      category: "necklaces",
      metal: "yellow",
      purity: 585,
      weight: 4.1,
      gender: "women",
      sizes: ["40", "45"],
      stones: ["гранат"],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "Кара / армянские дома",
      inStock: true,
      stockCount: 5,
      isHit: true,
      isNew: true,
      images: ["/images/product-necklace-pomegranate.jpg"],
      article: "N-NAR-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Наринэ Г.",
          rating: 5,
          text: "Искала именно гранат, не «просто кулон». Здесь и форма, и цвет камня настоящие.",
          date: "2026-04-22",
          city: "Гюмри",
        },
      ],
    }),
    p({
      id: "voske-radiance-tennis",
      sku: "VOSKE-585-B-022",
      slug: "braslet-tennis-siyanie",
      name: "Браслет теннисный «Сияние»",
      nameHy: "«Փայլ» թենիս ապարանջան",
      description:
        "Ряд камней в жёлтом золоте — формат, который сделали массовым хитом сети вроде SOKOLOV, но здесь плотность закрепки ближе к салонной. Замок-коробка с предохранителем. Вечерний браслет, который не стыдно надеть с шёлком.",
      price: 189000,
      oldPrice: 219000,
      category: "bracelets",
      metal: "yellow",
      purity: 585,
      weight: 8.6,
      gender: "women",
      sizes: ["17", "18", "19"],
      stones: ["фианит", "бриллиантовая огранка"],
      collection: "Сияние камней",
      origin: "russia",
      inspiredBy: "SOKOLOV",
      inStock: true,
      stockCount: 3,
      isHit: true,
      isNew: false,
      images: ["/images/product-bracelet-tennis.jpg"],
      article: "B-TENNIS-585",
      warrantyMonths: 24,
      rating: 4.8,
      reviews: [
        {
          author: "Екатерина В.",
          rating: 5,
          text: "Тяжёлый, «дорогой» на руке. Застёжка надёжная — проверяла специально.",
          date: "2026-03-30",
          city: "Санкт-Петербург",
        },
      ],
    }),
    p({
      id: "voske-ararat-figaro",
      sku: "VOSKE-585-C-031",
      slug: "tsep-figaro-ararat",
      name: "Цепь Фигаро «Арарат»",
      nameHy: "«Արարատ» ֆիգարո շղթա",
      description:
        "Мужская цепь плетения Фигаро из жёлтого золота 585. Плотное звено, заводской блеск в духе костромских производств вроде NEWGOLD: без лишней орнаментики, только вес металла и честный панцирь. Носится соло или с крестом.",
      price: 124500,
      category: "chains",
      metal: "yellow",
      purity: 585,
      weight: 18.4,
      gender: "men",
      sizes: ["50", "55", "60"],
      stones: [],
      collection: "Мужской характер",
      origin: "russia",
      inspiredBy: "NEWGOLD",
      inStock: true,
      stockCount: 4,
      isHit: false,
      isNew: false,
      images: ["/images/product-chain-figaro.jpg"],
      article: "C-FIGARO-585",
      warrantyMonths: 24,
      rating: 4.9,
      reviews: [
        {
          author: "Артём П.",
          rating: 5,
          text: "Вес чувствуется, не «проволока». Цвет золота насыщенный.",
          date: "2026-02-14",
          city: "Москва",
        },
      ],
    }),
    p({
      id: "voske-surb-khach",
      sku: "VOSKE-585-X-009",
      slug: "krest-armyanskiy-surb-khach",
      name: "Крест «Сурб Хач» с филигранью",
      nameHy: "«Սուրբ Խաչ» խաչ филигранով",
      description:
        "Армянский крест с растительной филигранью — не латинский четырёхконечник, а узнаваемый хачкар в миниатюре. Жёлтое золото 585, ручная проработка лучей. Талисман веры и семьи, который дарят на крещение и совершеннолетие.",
      price: 28900,
      category: "crosses",
      metal: "yellow",
      purity: 585,
      weight: 2.05,
      gender: "unisex",
      sizes: [],
      stones: [],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "Армянские ювелирные мастерские",
      inStock: true,
      stockCount: 12,
      isHit: true,
      isNew: false,
      images: ["/images/product-cross-armenian.jpg"],
      article: "X-KHACH-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Гагик М.",
          rating: 5,
          text: "Наконец крест, который выглядит армянским, а не «общецерковным».",
          date: "2026-01-18",
          city: "Ереван",
        },
      ],
    }),
    p({
      id: "voske-eternity-bands",
      sku: "VOSKE-585-W-003",
      slug: "obruchalnye-koltsa-vechnost",
      name: "Обручальные кольца «Вечность»",
      nameHy: "«Հավերժություն» ամուսնական մատանիներ",
      description:
        "Пара классических шин из жёлтого золота 585: женское 3.5 мм, мужское 5 мм, внутренняя комфортная линза. Эстетика московских заводских коллекций вроде МЮЗ — без камней, чтобы кольца жили десятилетиями и не цеплялись за будни.",
      price: 54300,
      oldPrice: 61000,
      category: "wedding",
      metal: "yellow",
      purity: 585,
      weight: 7.8,
      gender: "unisex",
      sizes: ["16", "16.5", "17", "17.5", "18", "18.5", "19", "20", "21"],
      stones: [],
      collection: "Свадебная",
      origin: "russia",
      inspiredBy: "МЮЗ",
      inStock: true,
      stockCount: 7,
      isHit: true,
      isNew: false,
      images: ["/images/product-wedding-bands.jpg"],
      article: "W-ETERNITY-585",
      warrantyMonths: 36,
      rating: 4.9,
      reviews: [
        {
          author: "Ирина и Павел",
          rating: 5,
          text: "Взяли пару сразу. Полировка зеркальная, кромка не режет палец.",
          date: "2026-06-01",
          city: "Москва",
        },
      ],
    }),
    p({
      id: "voske-rose-hoops",
      sku: "VOSKE-585-E-028",
      slug: "sergi-kongo-rozovoe-zoloto",
      name: "Серьги-конго из красного золота",
      nameHy: "Կարմիր ոսկու կոնգո ականջօղեր",
      description:
        "Средние конго из красного золота с дорожкой камней. Цвет металла — фирменный «русский красный», который любят в коллекциях EFREMOV: тёплый, почти медный рассвет, а не европейский розовый. Универсальны с пучком и с распущенными волосами.",
      price: 38700,
      category: "earrings",
      metal: "rose",
      purity: 585,
      weight: 3.9,
      gender: "women",
      sizes: [],
      stones: ["фианит"],
      collection: "Русская классика",
      origin: "russia",
      inspiredBy: "EFREMOV",
      inStock: true,
      stockCount: 9,
      isHit: false,
      isNew: true,
      images: ["/images/product-hoops-rose.jpg"],
      article: "E-HOOPS-585",
      warrantyMonths: 24,
      rating: 4.8,
      reviews: [],
    }),
    p({
      id: "voske-letter-locket",
      sku: "VOSKE-585-P-011",
      slug: "medalon-sekret-pismo",
      name: "Медальон-секрет «Письмо»",
      nameHy: "«Նամակ» մեդալիոն-գաղտնիք",
      description:
        "Открывающийся медальон из жёлтого золота с алмазной гранью. Внутри — два гнезда для миниатюр или локона. Романтическая вещь в традиции семейных домов: носят близко к сердцу, дарят на годовщину.",
      price: 42100,
      category: "pendants",
      metal: "yellow",
      purity: 585,
      weight: 3.2,
      gender: "women",
      sizes: ["45", "50"],
      stones: ["бриллиант"],
      collection: "Русская классика",
      origin: "russia",
      inspiredBy: "SUNLIGHT",
      inStock: true,
      stockCount: 6,
      isHit: false,
      isNew: true,
      images: ["/images/product-pendant-locket.jpg"],
      article: "P-LETTER-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Ольга Д.",
          rating: 5,
          text: "Положила фото дочки. Замок медальона плотный, не открывается сам.",
          date: "2026-07-02",
          city: "Сочи",
        },
      ],
    }),
    p({
      id: "voske-tsar-signet",
      sku: "VOSKE-585-R-044",
      slug: "persten-muzhskoy-tsar",
      name: "Перстень мужской «Царь»",
      nameHy: "«Ցար» տղամարդու մատանի",
      description:
        "Массивный печатка с овальной площадкой из жёлтого золота 585. Можно гравировать инициалы. Эстетика мужских витрин крупных сетей, но с более спокойной полировкой — без «спортивного» блеска.",
      price: 76800,
      category: "rings",
      metal: "yellow",
      purity: 585,
      weight: 9.1,
      gender: "men",
      sizes: ["19", "20", "21", "22"],
      stones: [],
      collection: "Мужской характер",
      origin: "russia",
      inspiredBy: "585*Золотой",
      inStock: true,
      stockCount: 4,
      isHit: false,
      isNew: false,
      images: ["/images/product-signet-ring.jpg"],
      article: "R-TSAR-585",
      warrantyMonths: 24,
      rating: 4.7,
      reviews: [],
    }),
    p({
      id: "voske-sirun-heart",
      sku: "VOSKE-585-B-008",
      slug: "braslet-serdtse-sirunush",
      name: "Браслет «Сирануш» с сердцем",
      nameHy: "«Սիրանուշ» ապարանջան սրտիկով",
      description:
        "Тонкий браслет-цепочка с шармом-сердцем. Имя Сирануш — «милая» по-армянски. Лёгкое золото 585 для ежедневной носки, как те модели, что разбирают в подарок на 8 марта в русских и армянских салонах.",
      price: 31400,
      oldPrice: 34900,
      category: "bracelets",
      metal: "yellow",
      purity: 585,
      weight: 2.4,
      gender: "women",
      sizes: ["16", "17", "18"],
      stones: [],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "SOKOLOV",
      inStock: true,
      stockCount: 11,
      isHit: true,
      isNew: false,
      images: ["/images/product-bracelet-heart.jpg"],
      article: "B-SIRUN-585",
      warrantyMonths: 24,
      rating: 4.9,
      reviews: [
        {
          author: "Алина Т.",
          rating: 5,
          text: "Нежный, не снимаю. Сердечко не разворачивается на руке.",
          date: "2026-03-08",
          city: "Москва",
        },
      ],
    }),
    p({
      id: "voske-ice-studs",
      sku: "VOSKE-585-E-002",
      slug: "pusety-brillianty-led",
      name: "Пусеты «Лёд» с бриллиантами",
      nameHy: "«Սառույց» ադամանդե պուսետներ",
      description:
        "Гвоздики из белого золота 585 с бриллиантами круглой огранки. Холодный металл, чистый блеск — формат, который в SUNLIGHT ставят в блок «на каждый день». Идеальная первая пара бриллиантов.",
      price: 52800,
      category: "earrings",
      metal: "white",
      purity: 585,
      weight: 1.28,
      gender: "women",
      sizes: [],
      stones: ["бриллиант"],
      collection: "Сияние камней",
      origin: "russia",
      inspiredBy: "SUNLIGHT",
      inStock: true,
      stockCount: 10,
      isHit: true,
      isNew: false,
      images: ["/images/product-studs-diamond.jpg"],
      article: "E-ICE-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Дарья Л.",
          rating: 5,
          text: "Белое золото не желтит. Камни ровные, закрутки удобные.",
          date: "2026-05-21",
          city: "Казань",
        },
      ],
    }),
    p({
      id: "voske-faith-necklace",
      sku: "VOSKE-585-N-019",
      slug: "kole-krest-vera",
      name: "Колье «Вера» с крестом",
      nameHy: "«Հավատ» վզնոց խաչով",
      description:
        "Якорная цепь и небольшой крест с бриллиантовыми искрами. Унисекс-украшение, которое носят и поверх водолазки, и на открытой шее. Сдержанная русская салонная классика.",
      price: 35600,
      category: "necklaces",
      metal: "yellow",
      purity: 585,
      weight: 3.55,
      gender: "unisex",
      sizes: ["45", "50", "55"],
      stones: ["бриллиант"],
      collection: "Русская классика",
      origin: "russia",
      inspiredBy: "МЮЗ",
      inStock: true,
      stockCount: 8,
      isHit: false,
      isNew: false,
      images: ["/images/product-necklace-cross.jpg"],
      article: "N-FAITH-585",
      warrantyMonths: 24,
      rating: 4.8,
      reviews: [],
    }),
    p({
      id: "voske-ararat-medallion",
      sku: "VOSKE-585-P-020",
      slug: "medalon-ararat",
      name: "Медальон «Арарат»",
      nameHy: "«Արարատ» մեդալիոն",
      description:
        "Круглый медальон с горельефом двух вершин Арарата. Жёлтое золото 585, матовое поле и полированные снега. Украшение-икона для тех, кто хранит Армению при себе — в Ереване, в Глендейле или в Москве.",
      price: 61200,
      category: "pendants",
      metal: "yellow",
      purity: 585,
      weight: 6.7,
      gender: "unisex",
      sizes: ["50", "55", "60"],
      stones: [],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "Армянские ювелирные дома",
      inStock: true,
      stockCount: 5,
      isHit: false,
      isNew: true,
      images: ["/images/product-medallion-ararat.jpg"],
      article: "P-ARARAT-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Вардан К.",
          rating: 5,
          text: "Рельеф глубокий, горы читаются. Ношу вместо обычного кулона.",
          date: "2026-04-07",
          city: "Ереван",
        },
      ],
    }),
    p({
      id: "voske-kids-blossom",
      sku: "VOSKE-585-K-004",
      slug: "detskie-sergi-tsvetok",
      name: "Детские серьги «Цветок»",
      nameHy: "Մանկական «Ծաղիկ» ականջօղեր",
      description:
        "Крошечные цветы из золота 585 с безопасными закрутками. Категория, без которой не обходится ни 585*Золотой, ни армянский семейный салон: первый золотой подарок на крестины или день рождения.",
      price: 9800,
      category: "kids",
      metal: "yellow",
      purity: 585,
      weight: 0.62,
      gender: "kids",
      sizes: [],
      stones: ["фианит"],
      collection: "Детская радость",
      origin: "russia",
      inspiredBy: "585*Золотой",
      inStock: true,
      stockCount: 15,
      isHit: true,
      isNew: false,
      images: ["/images/product-kids-earrings.jpg"],
      article: "K-BLOSSOM-585",
      warrantyMonths: 12,
      rating: 4.9,
      reviews: [
        {
          author: "Светлана Р.",
          rating: 5,
          text: "Лёгкие, дочка не жалуется. Закрутки с гипоаллергенной сталью внутри.",
          date: "2026-02-28",
          city: "Ростов-на-Дону",
        },
      ],
    }),
    p({
      id: "voske-sun-bangle",
      sku: "VOSKE-585-B-040",
      slug: "bengl-zoloto-solntse",
      name: "Браслет-бэнгл «Солнце»",
      nameHy: "«Արև» բանգլ ապարանջան",
      description:
        "Жёсткий полированный бэнгл из жёлтого золота. Один жест — и запястье «одето». Форма, которую держат в мужских и женских линейках PLATINA и крупных сетей: чистый металл, максимум света.",
      price: 95600,
      category: "bracelets",
      metal: "yellow",
      purity: 585,
      weight: 14.2,
      gender: "unisex",
      sizes: ["17", "18", "19"],
      stones: [],
      collection: "Русская классика",
      origin: "russia",
      inspiredBy: "PLATINA",
      inStock: true,
      stockCount: 3,
      isHit: false,
      isNew: false,
      images: ["/images/product-bangle-gold.jpg"],
      article: "B-SUN-585",
      warrantyMonths: 24,
      rating: 4.8,
      reviews: [],
    }),
    p({
      id: "voske-garnet-garden",
      sku: "VOSKE-585-R-018",
      slug: "koltso-granatovyy-sad",
      name: "Кольцо «Гранатовый сад»",
      nameHy: "«Նռան այգի» մատանի",
      description:
        "Коктейльное кольцо с овальным гранатом в окружении мелких камней. Цвет — гранат Еревана, оправа — жёлтое золото 585. Вещь для вечера и для фото, мост между армянским символом и русской любовью к крупным вставкам.",
      price: 73400,
      oldPrice: 81200,
      category: "rings",
      metal: "yellow",
      purity: 585,
      weight: 5.4,
      gender: "women",
      sizes: ["16", "16.5", "17", "17.5", "18"],
      stones: ["гранат", "фианит"],
      collection: "Армянское наследие",
      origin: "armenia",
      inspiredBy: "Кара",
      inStock: true,
      stockCount: 4,
      isHit: false,
      isNew: true,
      images: ["/images/product-ring-garnet.jpg"],
      article: "R-GARDEN-585",
      warrantyMonths: 24,
      rating: 5,
      reviews: [
        {
          author: "Элен С.",
          rating: 5,
          text: "Гранат живой, не чёрный. Кольцо заметное, но не вульгарное.",
          date: "2026-07-11",
          city: "Ереван",
        },
      ],
    }),
  ];
}
